#!/bin/sh -ex

## Fetch and unpack a version of the Bluray key database for libaacs
path="${HOME}/.config/aacs"

dbfile="${path}/KEYDB.cfg"
archive="${dbfile}.zip"
etag="${dbfile}.etag"

mkdir -p "$path"
curl --location --etag-compare "$etag" --etag-save "$etag" http://fvonline-db.bplaced.net/fv_download.php?lang=eng -o "$archive"
unzip "$archive" -p >"$dbfile".tmp
mv "$dbfile".tmp "$dbfile"
